site_name: Cosmotech Acceleration Library Docs

theme:
  name: material
  logo: assets/logo.png
  font:
    code: Fira Mono
  palette:
    scheme: slate
    primary: orange
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  custom_dir: docs/overrides

extra:
  version:
    provider: mike

nav:
  - Home: 'index.md'
  - Getting started:
    - Dependencies: 'dependencies.md'
  - References: references/
  - csm-data: cli/

markdown_extensions:
    - attr_list
    - mkdocs-click
    - tables
    - toc:
        title: "In this page"
        permalink: true
    - pymdownx.snippets

plugins:
  - search
  - mkdocstrings:
     default_handler: python
     handlers:
       python:
         options:
           docstring_style: sphinx
           line_lenth: 120
  - gen-files:
      scripts:
        - docs/scripts/generate_references.py
        - docs/scripts/generate_dependencies_markdown.py
        - docs/scripts/generate_index.py
  - literate-nav
  - mike
