site_name: Cosmotech Acceleration Library Docs
repo_url: https://github.com/Cosmo-Tech/CosmoTech-Acceleration-Library
repo_name: Cosmo-Tech/CosmoTech-Acceleration-Library
site_description: Acceleration library for CosmoTech cloud based solution development 
site_url: https://cosmo-tech.github.io/CosmoTech-Acceleration-Library/

theme:
  name: material
  logo: assets/logo.png
  font:
    code: Fira Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.footer
    - navigation.sections
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css
  - stylesheets/templates.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascript/tablesort.js

extra:
  version:
    provider: mike
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

nav:
  - Home: 'index.md'
  - Getting started:
      - Dependencies: 'dependencies.md'
  - Tutorials: tutorials/
  - References: references/
  - csm-data: csm-data/

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      title: "In this page"
      permalink: true
  - def_list
  - mkdocs-click
  - pymdownx.details
  - pymdownx.snippets:
      url_download: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg



plugins:
  - search:
      lang:
        - en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
            line_lenth: 120
  - gen-files:
      scripts:
        - docs/scripts/generate_references.py
        - docs/scripts/generate_dependencies_markdown.py
        - docs/scripts/generate_index.py
        - docs/scripts/generate_command_helps.py
  - mike
  - social
  - table-reader
  - awesome-pages
  - literate-nav
