nav:
  - Home: 'index.md'
  - Getting started:
      - Dependencies: 'dependencies.md'
      - Pull Request Checklist: 'pull_request.md'
  - Tutorials: tutorials/
#  - References: references/
  - csm-data: csm-data/
