name: tag_latest_release_gh_page
on:
  release:
    types: [released]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -e .[doc]
      - name: Extract version
        shell: bash
        run: echo "##[set-output name=version;]$(python -c 'from CosmoTech_Acceleration_Library import __version__; print(__version__)')"
        id: version
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: mike deploy --push --update-aliases ${{ steps.version.outputs.version }} latest
